
export const scheduleData = [
    "trader-scheduler-BTC-USD-medium_term-dev-schedule"
]

export const positionData = [
    {
        "global_product_id": "COINBASE.BTC.USD",
        "component_id": "01JVR5DN3G9SY6XM9QDY1VD5T6.ENTRY",
        "position_id": "01JVR5DN3GMR0B2F27F2FJB5NG",
        "ttl": null,
        "strategy_term": "MEDIUM_TERM",
        "order_id": "728b09be-177a-4993-bc2f-de11fd836dfb",
        "product_id": "BTC-USD",
        "user_id": "58b20d15-617e-5ae2-8874-6a9b70a7d712",
        "client_order_id": "cab706b4-74f5-4661-a987-1d33e56cef45",
        "order_configuration": {
            "market_market_ioc": {
                "quote_size": "1",
                "rfq_enabled": false,
                "rfq_disabled": false
            }
        },
        "edit_history": [],
        "leverage": "",
        "margin_type": "UNKNOWN_MARGIN_TYPE",
        "retail_portfolio_id": "2002ad99-74bf-4ea2-956c-ee8f40ded700",
        "originating_order_id": "",
        "attached_order_id": "",
        "attached_order_configuration": null,
        "side": "BUY",
        "status": "FILLED",
        "time_in_force": "IMMEDIATE_OR_CANCEL",
        "created_time": Date.now(),
        "completion_percentage": "100",
        "filled_size": "0.0964582926399911",
        "average_filled_price": "10.2900000000000029",
        "fee": "",
        "number_of_fills": "2",
        "filled_value": "0.9925558312655087",
        "pending_cancel": false,
        "size_in_quote": true,
        "total_fees": "0.0074441687344913",
        "size_inclusive_of_fees": true,
        "total_value_after_fees": "1",
        "trigger_status": "INVALID_ORDER_TYPE",
        "order_type": "MARKET",
        "reject_reason": "REJECT_REASON_UNSPECIFIED",
        "settled": true,
        "product_type": "SPOT",
        "reject_message": "",
        "cancel_message": "",
        "order_placement_source": "RETAIL_ADVANCED",
        "outstanding_hold_amount": "0",
        "is_liquidation": false,
        "last_fill_time": Date.now()
    },
    {
        "global_product_id": "COINBASE.BTC.USD",
        "component_id": "01JVR5DSNTV08NG2QFZPQVKT51.EXIT",
        "position_id": "01JVR5DN3GMR0B2F27F2FJB5NG",
        "ttl": 1748393749,
        "strategy_term": "MEDIUM_TERM",
        "order_id": "728b09be-177a-4993-bc2f-de11fd836dfb",
        "product_id": "BTC-USD",
        "user_id": "58b20d15-617e-5ae2-8874-6a9b70a7d712",
        "client_order_id": "cab706b4-74f5-4661-a987-1d33e56cef45",
        "order_configuration": {
            "stop_limit_stop_limit_gtc": {
                "base_size": "0.00001",
                "rfq_enabled": false,
                "rfq_disabled": false
            }
        },
        "edit_history": [],
        "leverage": "",
        "margin_type": "UNKNOWN_MARGIN_TYPE",
        "retail_portfolio_id": "2002ad99-74bf-4ea2-956c-ee8f40ded700",
        "originating_order_id": "",
        "attached_order_id": "",
        "attached_order_configuration": null,
        "side": "SELL",
        "status": "OPEN",
        "time_in_force": "IMMEDIATE_OR_CANCEL",
        "created_time": Date.now(),
        "completion_percentage": "100",
        "filled_size": "0.0964582926399911",
        "average_filled_price": "10.1900000000000029",
        "fee": "",
        "number_of_fills": "2",
        "filled_value": "0.9925558312655087",
        "pending_cancel": false,
        "size_in_quote": true,
        "total_fees": "0.0074441687344913",
        "size_inclusive_of_fees": true,
        "total_value_after_fees": "1",
        "trigger_status": "INVALID_ORDER_TYPE",
        "order_type": "STOP",
        "reject_reason": "REJECT_REASON_UNSPECIFIED",
        "settled": true,
        "product_type": "SPOT",
        "reject_message": "",
        "cancel_message": "",
        "order_placement_source": "RETAIL_ADVANCED",
        "outstanding_hold_amount": "0",
        "is_liquidation": false,
        "last_fill_time": Date.now()
    }
]
