name: Deploy DEV React Positions to S3

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        description: 'Enter the region'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ./mfes/positions
          npm install
      
      - name: Generate env files
        run: |
          cd ./mfes/positions
          echo "PROXY_API_BASE_URL=${{ secrets.PROXY_API_BASE_URL }}" >> .env

      - name: Build the application
        run: |
          cd ./mfes/positions
          AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }} npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd ./mfes/positions
          aws s3 sync dist/ s3://${{ secrets.FRONTEND_POSITIONS_BUCKET }} --delete