name: Deploy PROD React App to S3

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        description: 'Enter the region'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ./mfes/app
          npm install

      - name: Build the application
        run: |
          cd ./mfes/app
          AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL_PROD }} \
          POSITIONS_SERVICE_URL=${{ secrets.POSITIONS_SERVICE_URL_PROD }} \
          npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: |
          cd ./mfes/app
          aws s3 sync dist/ s3://${{ secrets.FRONTEND_APP_BUCKET_PROD }} --delete
