name: Deploy DEV App Cloudfront

on:
    workflow_dispatch:
      inputs:
        action:
          type: choice
          description: Pick action
          options:
          - deploy
          - destroy
        region:
          type: string
          required: true
          description: Pick region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10' 

      - name: Deploy Service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP: app
        run: |
          ENV=dev REGION=${{ inputs.region }} ./run ${{ inputs.action }}-service